SKILLS_CATALOGUE = [
    # ==========================================================
    # Telecom / Network Engineering
    # ==========================================================
    "RF Planning",
    "RF Optimization",
    "RAN Engineering",
    "RAN Optimization",
    "4G LTE",
    "5G NR",
    "Carrier Aggregation",
    "Massive MIMO",
    "Small Cells",
    "Indoor Coverage (DAS)",
    "Spectrum Management",
    "Drive Testing",
    "Cell Site Design",
    "Cell Site Commissioning",
    "Interference Management",
    "SON (Self-Organizing Networks)",
    "Core Network (EPC)",
    "5G Core (5GC)",
    "IMS",
    "VoLTE",
    "VoWiFi",
    "SIP",
    "SS7",
    "Diameter",
    "PCRF / PCF",
    "HSS / UDM",
    "HLR / HSS Concepts",
    "Charging / OCS",
    "Policy Control",
    "Roaming",
    "Interconnect",
    "Lawful Intercept (high-level)",
    "IP Routing",
    "IP Switching",
    "LAN / WAN Design",
    "MPLS",
    "BGP",
    "OSPF",
    "IS-IS",
    "Multicast",
    "QoS Engineering",
    "Traffic Engineering",
    "Peering",
    "CDN Concepts",
    "DNS",
    "DHCP",
    "IPAM",
    "NAT",
    "IPv6",
    "Network Automation",
    "Network Monitoring (NOC)",
    "Fault Management",
    "Performance Management",
    "Configuration Management",
    "Network Capacity Planning",
    "Transmission (DWDM)",
    "Optical Transport",
    "Microwave Backhaul",
    "Fiber Optics",
    "Splicing & Testing (OTDR)",
    "GPON",
    "XGS-PON",
    "Ethernet Access",
    "Carrier Ethernet",
    "SDN",
    "NFV",
    "vRAN Concepts",
    "Edge Computing (MEC) Concepts",
    "Wi-Fi Engineering",
    "Wi-Fi 6/6E",
    "Wi-Fi Troubleshooting",
    "Firewall Management",
    "Load Balancing",
    "WAF Concepts",
    "Proxy Concepts",
    "DDoS Mitigation Concepts",

    # ==========================================================
    # Cloud / Platforms / DevOps / SRE
    # ==========================================================
    "Linux Administration",
    "Windows Administration",
    "Virtualization (VMware)",
    "Storage (SAN/NAS) Concepts",
    "Kubernetes",
    "Docker",
    "Container Security",
    "CI/CD",
    "Infrastructure as Code (Terraform)",
    "Configuration Management (Ansible)",
    "SRE Practices",
    "Observability (Metrics)",
    "Observability (Logging)",
    "Observability (Tracing)",
    "Monitoring Tools (concepts)",
    "Incident Management",
    "Problem Management",
    "Change Management",
    "Release Management",
    "Runbooks & Playbooks",
    "Automation",
    "Scripting (Bash)",
    "Python",
    "PowerShell",
    "Java",
    "JavaScript",
    "TypeScript",
    "API Design",
    "API Integration",
    "Microservices",
    "Event-driven Architecture",
    "Message Queues (concepts)",
    "Git Version Control",
    "Software Testing",
    "Test Automation",
    "Performance Testing",
    "System Design",
    "Technical Documentation",

    # ==========================================================
    # Data / Analytics
    # ==========================================================
    "SQL",
    "NoSQL Databases",
    "Data Modeling",
    "Data Engineering",
    "ETL/ELT Pipelines",
    "Data Quality",
    "Data Governance",
    "BI & Reporting",
    "Dashboard Design",
    "Analytics",
    "Customer Insights",
    "Experimentation / A-B Testing (concepts)",
    "Python for Data",
    "Excel (Advanced)",
    "Statistics (Applied)",
    "Deep Learning",

    # ==========================================================
    # Security / Risk / Compliance
    # ==========================================================
    "Security Fundamentals",
    "Security Architecture",
    "Threat Modeling",
    "Vulnerability Management",
    "Penetration Testing Concepts",
    "Security Monitoring (SIEM)",
    "SOC Operations",
    "Incident Response (Security)",
    "Identity & Access Management (IAM)",
    "Privileged Access Management (PAM) Concepts",
    "Zero Trust",
    "Encryption",
    "PKI & Certificates",
    "Secure Coding Practices",
    "Privacy & Data Protection",
    "Risk Management",
    "Compliance & Controls",
    "Audit Readiness",
    "Business Continuity",
    "Disaster Recovery",

    # ==========================================================
    # Service Management / Operations / Field
    # ==========================================================
    "IT Service Management (ITIL)",
    "Service Desk Operations",
    "Customer Support",
    "Troubleshooting",
    "Root Cause Analysis",
    "Knowledge Management",
    "Major Incident Coordination",
    "On-call Operations",
    "Field Operations",
    "Site Health & Safety",
    "Vendor & Contractor Management",
    "Asset Management",
    "Change Advisory Board (CAB) Concepts",

    # ==========================================================
    # Commercial / Product / Delivery
    # ==========================================================
    "Product Management",
    "Product Ownership",
    "Roadmapping",
    "Requirements Gathering",
    "Stakeholder Management",
    "Agile Delivery",
    "Scrum",
    "Kanban",
    "Project Management",
    "Program Management",
    "Risk & Issue Management",
    "Budgeting & Forecasting",
    "Procurement",
    "Vendor Management",
    "Sales",
    "Pre-sales / Solutions Consulting",
    "Account Management",
    "Commercial Negotiation",
    "CRM Systems",
    "Billing Systems",
    "Pricing Concepts",

    # ==========================================================
    # Soft skills / Leadership
    # ==========================================================
    "Communication",
    "Presentation Skills",
    "Facilitation",
    "Negotiation",
    "Conflict Resolution",
    "Leadership",
    "Coaching & Mentoring",
    "People Management",
    "Performance Management",
    "Team Collaboration",
    "Time Management",
    "Prioritisation",
    "Critical Thinking",
    "Analytical Thinking",
    "Decision Making",
    "Adaptability",
    "Customer Empathy",
    "Process Improvement",
    "Continuous Improvement Mindset",
]
